export const content = {
  en: {
    logoBar: {
      label: "Trusted by companies across 3 countries",
    },
    benefits: {
      label: "Why automate now",
      headline: "Your business is losing money on every manual process.",
      sub: "While you juggle 12 tools and respond manually, your competitors close clients on autopilot — 24 hours a day.",
      subheadline:
        "While you juggle 12 tools and respond manually, your competitors close clients on autopilot — 24 hours a day.",
      badLabel: "Without automation",
      goodLabel: "With automation",
      bad1: "Leads lost after hours. Follow-up forgotten. Clients go to competitors while you sleep.",
      bad2: "8 disconnected tools: CRM here, email there, WhatsApp on your phone, calendar somewhere else.",
      bad3: "Business fully dependent on referrals with a natural ceiling. No way to scale.",
      good1: "Every lead answered in seconds, nurtured automatically and followed up until closed — 24/7.",
      good2: "One orbit: CRM, automations, scheduling, contracts and payments. One screen. Zero friction.",
      good3: "Online funnel capturing leads 24/7. Automatic Google reviews. Zero manual effort.",
      pain: [
        "Leads lost after hours. Follow-up forgotten. Clients go to competitors while you sleep.",
        "8 disconnected tools: CRM here, email there, WhatsApp on your phone, calendar somewhere else.",
        "Business fully dependent on referrals with a natural ceiling. No way to scale.",
      ],
      solution: [
        "Every lead answered in seconds, nurtured automatically and followed up until closed — 24/7.",
        "One orbit: CRM, automations, scheduling, contracts and payments. One screen. Zero friction.",
        "Online funnel capturing leads 24/7. Automatic Google reviews. Zero manual effort.",
      ],
      painLabel: "Without automation",
      solutionLabel: "With automation",
      grid: [
        { icon: "clock", title: "Time back", desc: "Automate repetitive tasks and focus on what generates revenue." },
        { icon: "dollar", title: "Zero leads lost", desc: "Every lead captured and nurtured automatically, 24/7." },
        { icon: "chart", title: "Full visibility", desc: "Dashboards and reports that show exactly where your money goes." },
        { icon: "robot", title: "AI working for you", desc: "Intelligent automations that learn and optimize your processes." },
        { icon: "scale", title: "Scale without hiring", desc: "Grow revenue without proportionally growing headcount." },
        { icon: "link", title: "Everything integrated", desc: "All your tools connected in one ecosystem. Zero manual data entry." },
      ],
    },
    cases: {
      label: "Cases",
      headline: "Real transformations.",
      title: "Real transformations.",
      scrollHint: "Scroll to navigate",
      problem: "Problem",
      solution: "Solution",
      result: "Result",
      problemLabel: "Problem",
      solutionLabel: "Solution",
      resultLabel: "Result",
    },
    services: {
      label: "Services",
      headline: "We adapt to your business. Not the other way around.",
      subheadline:
        "We analyze each company deeply and implement automations and systems tailored for scale, revenue growth and workforce reduction — running automatic, 24 hours a day.",
      mostRequested: "Most requested",
      cards: [
        {
          title: "GHL Implementation & RevOps",
          desc: "Full GHL ecosystem. Pipelines, automations, onboarding. Commercial, operational and financial in one system.",
          price: "Custom quote",
        },
        {
          title: "Automation & Integrations",
          desc: "n8n, GHL, Zapier. Any system with API: Stripe, Asaas, ClickUp, ZapSign, WhatsApp, Meta Ads, Google and more.",
          price: "Custom quote",
        },
        {
          title: "Quasar CRM",
          desc: "Our white-label all-in-one platform. CRM, automations, funnels, email, SMS, scheduling.",
          price: "quasarcrm.com",
        },
      ],
      footer: "If it has an API, we integrate it. If it's a repetitive process, we automate it.",
    },
    process: {
      label: "Process",
      headline: "From chaos to orbit in 4 steps.",
      title: "From chaos to orbit in 4 steps.",
      steps: [
        { title: "Discovery", desc: "We map your systems, processes and goals. Identify bottlenecks and automation opportunities." },
        { title: "Architecture", desc: "We design the full ecosystem before building. You approve each step." },
        { title: "Launch", desc: "We implement, test, integrate and train your team. Delivery by documented milestones." },
        { title: "Orbit", desc: "Post-launch support. Your business in permanent orbit." },
      ],
      step1: { title: "Discovery", desc: "We map your systems, processes and goals. We identify bottlenecks and automation opportunities." },
      step2: { title: "Architecture", desc: "We design the complete ecosystem before building. You approve every stage." },
      step3: { title: "Launch", desc: "We implement, test, integrate and train your team. Delivery by documented milestones." },
      step4: { title: "Orbit ✦", desc: "Post-launch support. Your business in permanent orbit." },
    },
    blog: {
      label: "Blog",
      headline: "Resources & insights.",
      viewAll: "View all articles →",
    },
    faq: {
      label: "FAQ",
      headline: "Everything you need to know.",
      items: [
        {
          q: "What if I invest and it doesn't work for my business?",
          a: "That's exactly why we start with a free Discovery call — to understand your business before proposing anything. We only take on projects where we're confident we can deliver results. Our process starts with a deep analysis phase where we map your current systems and design the solution together. You approve every step before we build. Contracts are structured in milestones, so you never pay for something you haven't seen working. In over 5 years and across 3 countries, we've never abandoned a project.",
          cta: "→ Start with a free 30-min call. No commitment.",
        },
        {
          q: "How long does an implementation take?",
          a: "Basic: 2-4 weeks. Complex with multiple integrations: 4-8 weeks. Everything defined and documented before we start.",
        },
        {
          q: "Do I need to already have GoHighLevel?",
          a: "No. We handle the full setup. Or use Quasar CRM, our ready-to-use white-label platform.",
        },
        {
          q: "Which systems can you integrate?",
          a: "Any system with an API: Stripe, Asaas, ClickUp, ZapSign, n8n, WhatsApp, Meta Ads, Google and more.",
        },
        {
          q: "How does payment work?",
          a: "By milestones. We accept Stripe, Wise, bank transfer and PIX. Contracts formalized via ZapSign.",
        },
      ],
    },
    ctaFinal: {
      label: "Ready?",
      headline: "Ready to enter orbit?",
      sub: "Free discovery call · 30 minutes · No commitment",
      whatsapp: "Talk on WhatsApp",
      schedule: "Schedule a Call",
      currencies: "Accepted: USD · EUR · BRL",
    },
    footer: {
      tagline: "Built to Scale.",
      links: ["Services", "Cases", "Process", "Blog", "Quasar CRM", "Contact"],
      legal: "28 W Flagler St — Miami, FL, USA · Brasil · EIN: 36-5068966 · CNPJ: 42.133.065/0001-55",
      copyright: "© 2025 Vida Digital Solutions LLC. All rights reserved.",
    },
  },
  pt: {
    logoBar: {
      label: "Empresas que confiam em nós em 3 países",
    },
    benefits: {
      label: "Por que automatizar agora",
      headline: "Seu negócio perde dinheiro em cada processo manual.",
      sub: "Enquanto você alterna entre 12 ferramentas e responde manualmente, seus concorrentes fecham clientes no piloto automático — 24 horas por dia.",
      subheadline:
        "Enquanto você alterna entre 12 ferramentas e responde manualmente, seus concorrentes fecham clientes no piloto automático — 24 horas por dia.",
      badLabel: "Sem automação",
      goodLabel: "Com automação",
      bad1: "Leads perdidos fora do horário. Follow-up esquecido. Clientes vão para concorrentes enquanto você dorme.",
      bad2: "8 ferramentas desconectadas: CRM aqui, email ali, WhatsApp no celular, agenda em outro lugar.",
      bad3: "Negócio 100% dependente de indicações com teto natural. Sem como escalar.",
      good1: "Cada lead respondido em segundos, nutrido automaticamente e acompanhado até fechar — 24/7.",
      good2: "Uma órbita: CRM, automações, agendamento, contratos e pagamentos. Uma tela. Zero atrito.",
      good3: "Funil online capturando leads 24/7. Reviews no Google automáticos. Zero esforço manual.",
      pain: [
        "Leads perdidos fora do horário. Follow-up esquecido. Clientes vão para concorrentes enquanto você dorme.",
        "8 ferramentas desconectadas: CRM aqui, email ali, WhatsApp no celular, agenda em outro lugar.",
        "Negócio 100% dependente de indicações com teto natural. Sem como escalar.",
      ],
      solution: [
        "Cada lead respondido em segundos, nutrido automaticamente e acompanhado até fechar — 24/7.",
        "Uma órbita: CRM, automações, agendamento, contratos e pagamentos. Uma tela. Zero atrito.",
        "Funil online capturando leads 24/7. Reviews no Google automáticos. Zero esforço manual.",
      ],
      painLabel: "Sem automação",
      solutionLabel: "Com automação",
      grid: [
        { icon: "clock", title: "Tempo de volta", desc: "Automatize tarefas repetitivas e foque no que gera receita." },
        { icon: "dollar", title: "Zero leads perdidos", desc: "Cada lead capturado e nutrido automaticamente, 24/7." },
        { icon: "chart", title: "Visibilidade total", desc: "Dashboards e relatórios que mostram exatamente onde seu dinheiro vai." },
        { icon: "robot", title: "IA trabalhando por você", desc: "Automações inteligentes que aprendem e otimizam seus processos." },
        { icon: "scale", title: "Escale sem contratar", desc: "Aumente receita sem aumentar proporcionalmente a equipe." },
        { icon: "link", title: "Tudo integrado", desc: "Todas as ferramentas conectadas em um ecossistema. Zero entrada manual." },
      ],
    },
    cases: {
      label: "Cases",
      headline: "Transformações reais.",
      title: "Transformações reais.",
      scrollHint: "Role para navegar",
      problem: "Problema",
      solution: "Solução",
      result: "Resultado",
      problemLabel: "Problema",
      solutionLabel: "Solução",
      resultLabel: "Resultado",
    },
    services: {
      label: "Serviços",
      headline: "Nos adaptamos ao seu negócio. Não o contrário.",
      subheadline:
        "Analisamos cada empresa profundamente e implementamos automações e sistemas sob medida para escala, crescimento de receita e redução de força de trabalho — funcionando automático, 24 horas por dia.",
      mostRequested: "Mais solicitado",
      cards: [
        {
          title: "Implementação GHL & RevOps",
          desc: "Ecossistema GHL completo. Pipelines, automações, onboarding. Comercial, operacional e financeiro em um sistema.",
          price: "Orçamento personalizado",
        },
        {
          title: "Automação & Integrações",
          desc: "n8n, GHL, Zapier. Qualquer sistema com API: Stripe, Asaas, ClickUp, ZapSign, WhatsApp, Meta Ads, Google e mais.",
          price: "Orçamento personalizado",
        },
        {
          title: "Quasar CRM",
          desc: "Nossa plataforma all-in-one white-label. CRM, automações, funis, email, SMS, agendamento.",
          price: "quasarcrm.com",
        },
      ],
      footer: "Se tem API, integramos. Se é processo repetitivo, automatizamos.",
    },
    process: {
      label: "Processo",
      headline: "Do caos à órbita em 4 etapas.",
      title: "Do caos à órbita em 4 etapas.",
      steps: [
        { title: "Discovery", desc: "Mapeamos seus sistemas, processos e objetivos. Identificamos gargalos e oportunidades de automação." },
        { title: "Arquitetura", desc: "Desenhamos o ecossistema completo antes de construir. Você aprova cada etapa." },
        { title: "Lançamento", desc: "Implementamos, testamos, integramos e treinamos seu time. Entrega por milestones documentados." },
        { title: "Órbita", desc: "Suporte pós-lançamento. Seu negócio em órbita permanente." },
      ],
      step1: { title: "Discovery", desc: "Mapeamos seus sistemas, processos e objetivos. Identificamos gargalos e oportunidades de automação." },
      step2: { title: "Arquitetura", desc: "Desenhamos o ecossistema completo antes de construir. Você aprova cada etapa." },
      step3: { title: "Lançamento", desc: "Implementamos, testamos, integramos e treinamos seu time. Entrega por milestones documentados." },
      step4: { title: "Órbita ✦", desc: "Suporte pós-lançamento. Seu negócio em órbita permanente." },
    },
    blog: {
      label: "Blog",
      headline: "Recursos e insights.",
      viewAll: "Ver todos os artigos →",
    },
    faq: {
      label: "FAQ",
      headline: "Tudo o que você precisa saber.",
      items: [
        {
          q: "E se eu investir e não funcionar para o meu negócio?",
          a: "É exatamente por isso que começamos com uma Discovery Call gratuita — para entender seu negócio antes de propor qualquer coisa. Só aceitamos projetos onde temos confiança de entregar resultados. Nosso processo começa com uma fase de análise profunda onde mapeamos seus sistemas atuais e desenhamos a solução juntos. Você aprova cada etapa antes de construirmos. Contratos são estruturados em milestones, então você nunca paga por algo que não viu funcionando. Em mais de 5 anos e em 3 países, nunca abandonamos um projeto.",
          cta: "→ Comece com uma call gratuita de 30 min. Sem compromisso.",
        },
        {
          q: "Quanto tempo leva uma implementação?",
          a: "Básica: 2-4 semanas. Complexa com múltiplas integrações: 4-8 semanas. Tudo definido e documentado antes de começar.",
        },
        {
          q: "Preciso já ter GoHighLevel?",
          a: "Não. Cuidamos de toda a configuração. Ou use o Quasar CRM, nossa plataforma white-label pronta para uso.",
        },
        {
          q: "Quais sistemas vocês integram?",
          a: "Qualquer sistema com API: Stripe, Asaas, ClickUp, ZapSign, n8n, WhatsApp, Meta Ads, Google e mais.",
        },
        {
          q: "Como funciona o pagamento?",
          a: "Por milestones. Aceitamos Stripe, Wise, transferência bancária e PIX. Contratos formalizados via ZapSign.",
        },
      ],
    },
    ctaFinal: {
      label: "Pronto?",
      headline: "Pronto para entrar em órbita?",
      sub: "Discovery call gratuita · 30 minutos · Sem compromisso",
      whatsapp: "Falar no WhatsApp",
      schedule: "Agendar uma Call",
      currencies: "Aceito: USD · EUR · BRL",
    },
    footer: {
      tagline: "Built to Scale.",
      links: ["Serviços", "Cases", "Processo", "Blog", "Quasar CRM", "Contato"],
      legal: "28 W Flagler St — Miami, FL, USA · Brasil · EIN: 36-5068966 · CNPJ: 42.133.065/0001-55",
      copyright: "© 2025 Vida Digital Solutions LLC. Todos os direitos reservados.",
    },
  },
  es: {
    logoBar: {
      label: "Empresas que confían en nosotros en 3 países",
    },
    benefits: {
      label: "Por qué automatizar ahora",
      headline: "Tu negocio pierde dinero en cada proceso manual.",
      sub: "Mientras alternas entre 12 herramientas y respondes manualmente, tus competidores cierran clientes en piloto automático — 24 horas al día.",
      subheadline:
        "Mientras alternas entre 12 herramientas y respondes manualmente, tus competidores cierran clientes en piloto automático — 24 horas al día.",
      badLabel: "Sin automatización",
      goodLabel: "Con automatización",
      bad1: "Leads perdidos fuera de horario. Follow-up olvidado. Clientes van a competidores mientras duermes.",
      bad2: "8 herramientas desconectadas: CRM aquí, email allá, WhatsApp en el celular, agenda en otro lugar.",
      bad3: "Negocio 100% dependiente de referencias con techo natural. Sin forma de escalar.",
      good1: "Cada lead respondido en segundos, nutrido automáticamente y seguido hasta cerrar — 24/7.",
      good2: "Una órbita: CRM, automatizaciones, agenda, contratos y pagos. Una pantalla. Cero fricción.",
      good3: "Embudo online capturando leads 24/7. Reviews en Google automáticos. Cero esfuerzo manual.",
      pain: [
        "Leads perdidos fuera de horario. Follow-up olvidado. Clientes van a competidores mientras duermes.",
        "8 herramientas desconectadas: CRM aquí, email allá, WhatsApp en el celular, agenda en otro lugar.",
        "Negocio 100% dependiente de referencias con techo natural. Sin forma de escalar.",
      ],
      solution: [
        "Cada lead respondido en segundos, nutrido automáticamente y seguido hasta cerrar — 24/7.",
        "Una órbita: CRM, automatizaciones, agenda, contratos y pagos. Una pantalla. Cero fricción.",
        "Embudo online capturando leads 24/7. Reviews en Google automáticos. Cero esfuerzo manual.",
      ],
      painLabel: "Sin automatización",
      solutionLabel: "Con automatización",
      grid: [
        { icon: "clock", title: "Tiempo de vuelta", desc: "Automatiza tareas repetitivas y enfócate en lo que genera ingresos." },
        { icon: "dollar", title: "Cero leads perdidos", desc: "Cada lead capturado y nutrido automáticamente, 24/7." },
        { icon: "chart", title: "Visibilidad total", desc: "Dashboards e informes que muestran exactamente dónde va tu dinero." },
        { icon: "robot", title: "IA trabajando por ti", desc: "Automatizaciones inteligentes que aprenden y optimizan tus procesos." },
        { icon: "scale", title: "Escala sin contratar", desc: "Aumenta ingresos sin aumentar proporcionalmente el equipo." },
        { icon: "link", title: "Todo integrado", desc: "Todas las herramientas conectadas en un ecosistema. Cero entrada manual." },
      ],
    },
    cases: {
      label: "Cases",
      headline: "Transformaciones reales.",
      title: "Transformaciones reales.",
      scrollHint: "Desplázate para navegar",
      problem: "Problema",
      solution: "Solución",
      result: "Resultado",
      problemLabel: "Problema",
      solutionLabel: "Solución",
      resultLabel: "Resultado",
    },
    services: {
      label: "Servicios",
      headline: "Nos adaptamos a tu negocio. No al revés.",
      subheadline:
        "Analizamos cada empresa profundamente e implementamos automatizaciones y sistemas a medida para escala, crecimiento de ingresos y reducción de fuerza laboral — funcionando automático, 24 horas al día.",
      mostRequested: "Más solicitado",
      cards: [
        {
          title: "Implementación GHL & RevOps",
          desc: "Ecosistema GHL completo. Pipelines, automatizaciones, onboarding. Comercial, operativo y financiero en un sistema.",
          price: "Presupuesto personalizado",
        },
        {
          title: "Automatización & Integraciones",
          desc: "n8n, GHL, Zapier. Cualquier sistema con API: Stripe, Asaas, ClickUp, ZapSign, WhatsApp, Meta Ads, Google y más.",
          price: "Presupuesto personalizado",
        },
        {
          title: "Quasar CRM",
          desc: "Nuestra plataforma all-in-one white-label. CRM, automatizaciones, embudos, email, SMS, agenda.",
          price: "quasarcrm.com",
        },
      ],
      footer: "Si tiene API, lo integramos. Si es un proceso repetitivo, lo automatizamos.",
    },
    process: {
      label: "Proceso",
      headline: "Del caos a la órbita en 4 pasos.",
      title: "Del caos a la órbita en 4 pasos.",
      steps: [
        { title: "Discovery", desc: "Mapeamos tus sistemas, procesos y objetivos. Identificamos cuellos de botella y oportunidades de automatización." },
        { title: "Arquitectura", desc: "Diseñamos el ecosistema completo antes de construir. Apruebas cada paso." },
        { title: "Lanzamiento", desc: "Implementamos, probamos, integramos y entrenamos a tu equipo. Entrega por milestones documentados." },
        { title: "Órbita", desc: "Soporte post-lanzamiento. Tu negocio en órbita permanente." },
      ],
      step1: { title: "Discovery", desc: "Mapeamos tus sistemas, procesos y objetivos. Identificamos cuellos de botella y oportunidades de automatización." },
      step2: { title: "Arquitectura", desc: "Diseñamos el ecosistema completo antes de construir. Tú apruebas cada etapa." },
      step3: { title: "Lanzamiento", desc: "Implementamos, probamos, integramos y capacitamos a tu equipo. Entrega por milestones documentados." },
      step4: { title: "Órbita ✦", desc: "Soporte post-lanzamiento. Tu negocio en órbita permanente." },
    },
    blog: {
      label: "Blog",
      headline: "Recursos e insights.",
      viewAll: "Ver todos los artículos →",
    },
    faq: {
      label: "FAQ",
      headline: "Todo lo que necesitas saber.",
      items: [
        {
          q: "¿Y si invierto y no funciona para mi negocio?",
          a: "Exactamente por eso comenzamos con una Discovery Call gratuita — para entender tu negocio antes de proponer nada. Solo aceptamos proyectos donde tenemos confianza de entregar resultados. Nuestro proceso comienza con una fase de análisis profundo donde mapeamos tus sistemas actuales y diseñamos la solución juntos. Apruebas cada paso antes de construir. Los contratos están estructurados en milestones, así que nunca pagas por algo que no has visto funcionando. En más de 5 años y en 3 países, nunca abandonamos un proyecto.",
          cta: "→ Comienza con una llamada gratuita de 30 min. Sin compromiso.",
        },
        {
          q: "¿Cuánto tiempo toma una implementación?",
          a: "Básica: 2-4 semanas. Compleja con múltiples integraciones: 4-8 semanas. Todo definido y documentado antes de comenzar.",
        },
        {
          q: "¿Necesito ya tener GoHighLevel?",
          a: "No. Nos encargamos de toda la configuración. O usa Quasar CRM, nuestra plataforma white-label lista para usar.",
        },
        {
          q: "¿Qué sistemas pueden integrar?",
          a: "Cualquier sistema con API: Stripe, Asaas, ClickUp, ZapSign, n8n, WhatsApp, Meta Ads, Google y más.",
        },
        {
          q: "¿Cómo funciona el pago?",
          a: "Por milestones. Aceptamos Stripe, Wise, transferencia bancaria y PIX. Contratos formalizados vía ZapSign.",
        },
      ],
    },
    ctaFinal: {
      label: "¿Listo?",
      headline: "¿Listo para entrar en órbita?",
      sub: "Discovery call gratuita · 30 minutos · Sin compromiso",
      whatsapp: "Hablar por WhatsApp",
      schedule: "Agendar una llamada",
      currencies: "Aceptado: USD · EUR · BRL",
    },
    footer: {
      tagline: "Built to Scale.",
      links: ["Servicios", "Cases", "Proceso", "Blog", "Quasar CRM", "Contacto"],
      legal: "28 W Flagler St — Miami, FL, USA · Brasil · EIN: 36-5068966 · CNPJ: 42.133.065/0001-55",
      copyright: "© 2025 Vida Digital Solutions LLC. Todos los derechos reservados.",
    },
  },
} as const;
